# Generated by Django 6.0 on 2026-01-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmodrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('location', models.CharField(max_length=300, verbose_name='Местоположение')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
            ],
            options={
                'verbose_name': 'Космодром',
                'verbose_name_plural': 'Космодромы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Производитель')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('rocket_type', models.CharField(choices=[('orbital', 'Орбитальная'), ('suborbital', 'Суборбитальная'), ('heavy', 'Тяжёлая'), ('super_heavy', 'Сверхтяжёлая')], default='orbital', max_length=20, verbose_name='Тип ракеты')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('retired', 'Выведена из эксплуатации'), ('development', 'В разработке')], default='active', max_length=20, verbose_name='Статус')),
                ('first_flight', models.DateField(blank=True, null=True, verbose_name='Первый полёт')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Высота (м)')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Диаметр (м)')),
                ('mass', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Масса (т)')),
                ('payload_to_leo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Полезная нагрузка на НОО (кг)')),
                ('stages', models.IntegerField(default=2, verbose_name='Количество ступеней')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ракета',
                'verbose_name_plural': 'Ракеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=300, verbose_name='Название миссии')),
                ('launch_date', models.DateTimeField(verbose_name='Дата и время запуска')),
                ('status', models.CharField(choices=[('success', 'Успешный'), ('failure', 'Неудачный'), ('partial', 'Частично успешный'), ('planned', 'Запланирован')], default='planned', max_length=20, verbose_name='Статус')),
                ('payload', models.CharField(blank=True, max_length=500, verbose_name='Полезная нагрузка')),
                ('orbit', models.CharField(blank=True, max_length=100, verbose_name='Орбита')),
                ('description', models.TextField(blank=True, verbose_name='Описание миссии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cosmodrome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='rockets.cosmodrome', verbose_name='Космодром')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='rockets.rocket', verbose_name='Ракета')),
            ],
            options={
                'verbose_name': 'Запуск',
                'verbose_name_plural': 'Запуски',
                'ordering': ['-launch_date'],
            },
        ),
    ]
