# Generated by Django 6.0 on 2026-01-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rocket',
            name='first_flight',
        ),
        migrations.AddField(
            model_name='rocket',
            name='first_flight_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год первого полёта'),
        ),
    ]
